<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="3" tests="6" time="0.122" timestamp="2021-06-11T14:46:33.031096" hostname="DESKTOP-4MBJ0IM"><testcase classname="test_addition" name="test_add_1" time="0.001"><skipped type="pytest.skip" message="unconditional skip">D:\workspaces\projects\m5d4\test_addition.py:7: unconditional skip</skipped></testcase><testcase classname="test_addition" name="test_add_2" time="0.001"><skipped type="pytest.skip" message="unconditional skip">D:\workspaces\projects\m5d4\test_addition.py:11: unconditional skip</skipped></testcase><testcase classname="test_addition" name="test_add_3" time="0.001" /><testcase classname="test_addition" name="test_add_4" time="0.001"><skipped type="pytest.xfail" message="" /></testcase><testcase classname="test_addition" name="test_add_5" time="0.001" /><testcase classname="test_addition" name="test_add_6" time="0.001"><failure message="AssertionError: failed&#10;assert 5 == 6&#10;  +5&#10;  -6">def test_add_6():
&gt;   	assert 3+2 == 6,"failed"
E    AssertionError: failed
E    assert 5 == 6
E      +5
E      -6

test_addition.py:27: AssertionError</failure></testcase></testsuite></testsuites>